# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [8]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype.name)

2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [9]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [15]:
print(f"Elementwise Sub B-C:\n{B - C}")
print(f"Elementwise mul B*C:\n{B * C}")
print(f"Matrix mul B@C:\n{B @ C}")

Elementwise Sub B-C:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Elementwise mul B*C:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
Matrix mul B@C:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [16]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
# Exponentiate each number elementwise
print(f"Exponentiated matrix (np.exp(B)): \n {np.exp(B)}\n")
print(f"Minimum value in the matrix: \n {np.min(B)}\n")
print(f"Minimum value in each row: \n {(np.min(B, axis=1))}\n")
print(f"Minimum value in each column:\n {(np.min(B, axis=0))}\n")
print(f"Index of minimum value in the matrix:\n {(np.argmin(B))}\n")
print(f"Index of minimum value in each row:\n {(np.argmin(B, axis=1))}\n")
print(f"Sum of all elements in the matrix: \n {np.sum(B)} \n")
print(f"Mean of each column:\n {(np.mean(B, axis=0))}\n")
print(f"Median of each column:\n {(np.median(B, axis=0))}\n")



Exponentiated matrix (np.exp(B)): 
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the matrix: 
 1

Minimum value in each row: 
 [1 4 7]

Minimum value in each column:
 [1 2 3]

Index of minimum value in the matrix:
 0

Index of minimum value in each row:
 [0 0 0]

Sum of all elements in the matrix: 
 45 

Mean of each column:
 [4. 5. 6.]

Median of each column:
 [4. 5. 6.]



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

In [ ]:
A[1] returns second row, 2D array of shape(x,y) not a single value.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?


In [45]:
A=np.arange(0, 21).reshape(3, 7)
print(A)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [42]:
for i in A:
    print(i)

[0 1 2 3 4 5 6]
[ 7  8  9 10 11 12 13]
[14 15 16 17 18 19 20]


In [43]:
for i in A.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [48]:
a = np.arange(30) # Creates a 1D array
b = a.reshape((2, 3, -1)) #Reshapes the 1D array into a 3D array with shape (2, 3, 30/2*3).
print(a)
print()

print(b)
# creates 2 blocks where 3 rows with 5 columns in each row

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [49]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)
# So it behaves like adding [1, 1] to every row.

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [50]:
v1 = np.array([1, 2, 3])
print(v1 + 1)
#uses broadcasting it adds 1 to each element of v1.


[2 3 4]


In [51]:
A = np.arange(1, 5).reshape(2,2)
print(A)
#creates an array [1, 2, 3, 4] and then reshaped into a 2×2 matrix

b = np.array([2, 2])
print(b)
creates a 1D array (a vector)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [69]:
def add_mult_matrx(m1, m2, operation):
     if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise TypeError("One or both matrxis not Numpy array.")

     if operation not in ['add', 'multiply']:
        raise ValueError("wrong operation")

     if operation == 'add':
        if m1.shape != m2.shape:
            raise ValueError("not the same shape.")
        return m1 + m2

     elif operation == 'multiply':
        if m1.shape[1] != m2.shape[0]:
            raise ValueError("not the same number of columns and rows")
        return m1 @ m2


v1 = np.array([1, 2, 3, 4, 5])
v2 = v1[1:4]  # [2, 3, 4]

result = add_mult_matrx(v1[0:3].reshape(1, 3), v2.reshape(1, 3), 'add')
print(result)

A = v1[0:3].reshape(1, 3)
B = v2.reshape(3, 1)

result = add_mult_matrx(A, B, 'multiply')
print(result)

[[3 5 7]]
[[20]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [98]:
print("exercises in chapter 10.1")
x = np.array([3, 4])
print(x,"\n")
print(x.ndim,"-", x.shape,"\n")
print(5 * x,"\n")
print(3 * x,"\n")
print((5 * x)+(3 * x),"\n")
print(8 * x,"\n")

print("exercises in chapter 10.1.2")
v = np.array([3, 7, 0, 11]).reshape(4, 1)
print(v, "\n")
print(v.ndim,"-", v.shape, "\n")
print(5*v, "\n")
print(2*v, "\n")
print(5*v+2*v, "\n")
print(4*v+2*v, "\n")
v_T = v.T
print(v_T)
print(v_T.ndim,"-", v_T.shape, "\n")

print("exercises in chapter 10.1.3", "\n")
v1 = np.array([4, 3, 1, 5]).reshape(1, 4)
v2 = np.array([2, 3, 1, 1]).reshape(1, 4)
print(np.linalg.norm(v1), "\n")
print(np.linalg.norm(v2), "\n")
print(np.linalg.norm(v1 - v2), "\n")


exercises in chapter 10.1
[3 4] 

1 - (2,) 

[15 20] 

[ 9 12] 

[24 32] 

[24 32] 

exercises in chapter 10.1.2
[[ 3]
 [ 7]
 [ 0]
 [11]] 

2 - (4, 1) 

[[15]
 [35]
 [ 0]
 [55]] 

[[ 6]
 [14]
 [ 0]
 [22]] 

[[21]
 [49]
 [ 0]
 [77]] 

[[18]
 [42]
 [ 0]
 [66]] 

[[ 3  7  0 11]]
2 - (1, 4) 

exercises in chapter 10.1.3 

7.14142842854285 

3.872983346207417 

4.47213595499958 



### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 


In [135]:
print("exercises in chapter 10.2.1", "\n")
A = np.array([2, 1, -1, 1,-1, 1]).reshape(2, 3)
B = np.array([4, -2, 1, 2,-4,-2]).reshape(2, 3)
C = np.array([1, 2, 2, 1]).reshape(2, 2)
D = np.array([3, 4, 4, 3]).reshape(2, 2)
E = np.array([2, 1]).reshape(2, 1)
I = np.array([1, 0, 0, 1]).reshape(2, 2)
print(A, "\n")
print(B, "\n")
print(C, "\n")
print(D, "\n")
print(E, "\n")
print(I, "\n")

print("ex")
print("a: \n", 2*A,"\n")
print("b: \n", B-2*A,"\n")
print("c: \n", 3*C-2*E,"\n")
print("d: \n", 2*D-3*C,"\n")
print("e: \n", D.T + 2 * D, "\n")
print("f: \n", 2*C.T + 2*D.T, "\n")
print("g: \n", "A.T - B ","  rätt bli  ", A.T - B.T, "\n")
print("h: \n", "A @ C ",  "rätt bli ",  A.T @ C, "\n")
print("i: \n", C @ D, "\n")
print("j: \n", C @ B, "\n")
print("k: \n", C @ I, "\n")
print("l: \n", A.T * B.T, "\n")


print("exercises in chapter 10.2.2", "\n")
A = np.array([2, 3, 4, 5, 4, 1]).reshape(2, 3)
print("i: \n", A @ A.T, "\n")

print("exercises in chapter 10.2.3", "\n")
A = np.array([1, 2, 2, 4]).reshape(2, 2)
B = np.array([2, 1, 1, 3]).reshape(2, 2)
C = np.array([4, 3, 0, 2]).reshape(2, 2)

print(A, "\n")
print(B, "\n")
print(C, "\n")
res1 = np.array_equal(A @ B, A @ C)
res2 = not np.array_equal(B, C)
print(res1)
print(res2)
      


exercises in chapter 10.2.1 

[[ 2  1 -1]
 [ 1 -1  1]] 

[[ 4 -2  1]
 [ 2 -4 -2]] 

[[1 2]
 [2 1]] 

[[3 4]
 [4 3]] 

[[2]
 [1]] 

[[1 0]
 [0 1]] 

ex
a: 
 [[ 4  2 -2]
 [ 2 -2  2]] 

b: 
 [[ 0 -4  3]
 [ 0 -2 -4]] 

c: 
 [[-1  2]
 [ 4  1]] 

d: 
 [[3 2]
 [2 3]] 

e: 
 [[ 9 12]
 [12  9]] 

f: 
 [[ 8 12]
 [12  8]] 

g: 
 A.T - B    rätt bli   [[-2 -1]
 [ 3  3]
 [-2  3]] 

h: 
 A @ C  rätt bli  [[ 4  5]
 [-1  1]
 [ 1 -1]] 

i: 
 [[11 10]
 [10 11]] 

j: 
 [[  8 -10  -3]
 [ 10  -8   0]] 

k: 
 [[1 2]
 [2 1]] 

l: 
 [[ 8  2]
 [-2  4]
 [-1 -2]] 

exercises in chapter 10.2.2 

i: 
 [[29 26]
 [26 42]] 

exercises in chapter 10.2.3 

[[1 2]
 [2 4]] 

[[2 1]
 [1 3]] 

[[4 3]
 [0 2]] 

True
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [162]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)



[0 1 2 3]
[2 3]


In [163]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [164]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [165]:
print(np.shares_memory(v1, v2))


True


In [152]:
#No because they share memory
# v2 = v1[-2:].copy() creates an independent copy